global:
  image:
    repository: gimral/beam-app
    tag: '1.0.2'

  jobmanager:
    additionalCommand:
    command: >-
      cp $FLINK_HOME/conf/flink-conf.yaml.tpl $FLINK_HOME/conf/flink-conf.yaml &&
      $FLINK_HOME/bin/standalone-job.sh start-foreground --job-classname org.example.kafkaoffset.MultipleKafkaOperatorsApp --parallelism=1 --runner=FlinkRunner --kafkaBrokers=kafka-cp-kafka.kafka.svc.cluster.local:9092;

  taskmanager:
    replicaCount: 1
    additionalCommand: